import type { components } from "./api-types";

// Convenient aliases onto the OpenAPI-generated schemas (lib/api-types.ts, regenerated by
// `npm run gen:types` from ../docs/sotohp-api-docs.json — see Makefile `ui` target) so call
// sites don't spell out `components["schemas"][...]` everywhere.
export type Media = components["schemas"]["Media"];
export type MediaLocation = components["schemas"]["MediaLocation"];
export type MediaSelector = components["schemas"]["MediaSelector"];
export type Original = components["schemas"]["Original"];
export type Bag = components["schemas"]["Bag"];
export type BagUpdate = components["schemas"]["BagUpdate"];
export type Owner = components["schemas"]["Owner"];
export type OwnerCreate = components["schemas"]["OwnerCreate"];
export type OwnerUpdate = components["schemas"]["OwnerUpdate"];
export type Store = components["schemas"]["Store"];
export type StoreCreate = components["schemas"]["StoreCreate"];
export type StoreUpdate = components["schemas"]["StoreUpdate"];
export type Person = components["schemas"]["Person"];
export type PersonCreate = components["schemas"]["PersonCreate"];
export type PersonUpdate = components["schemas"]["PersonUpdate"];
export type DetectedFace = components["schemas"]["DetectedFace"];

// A cheap cache-busting token for faceImageUrl(): changes whenever the crop's box does, which is
// exactly when the underlying cached image file gets regenerated (see faceImageUrl's comment).
export function faceBoxVersion(face: Pick<DetectedFace, "box">): string {
  const b = face.box;
  return `${b.x},${b.y},${b.width},${b.height}`;
}
export type FaceCreate = components["schemas"]["FaceCreate"];
export type OriginalFaces = components["schemas"]["OriginalFaces"];
export type Portfolio = components["schemas"]["Portfolio"];
export type PortfolioCreate = components["schemas"]["PortfolioCreate"];
export type PortfolioUpdate = components["schemas"]["PortfolioUpdate"];
export type Asset = components["schemas"]["Asset"];
export type BoundingBox = components["schemas"]["BoundingBox"];
export type State = components["schemas"]["State"];
export type Location = components["schemas"]["Location"];
export type SynchronizeStatus = {
  running: boolean;
  lastUpdated?: string;
  checkedCount: number;
  processedCount: number;
  startedAt?: string;
};
export type ClientConfig = components["schemas"]["ApiClientConfig"];

export interface MediaUpdateBody {
  description?: string;
  starred: boolean;
  keywords?: string[];
  orientation?: Media["orientation"];
  shootDateTime?: string;
  userDefinedLocation?: Location;
}

export interface Auth {
  getToken: () => string | null | undefined;
  refreshToken?: () => Promise<unknown>;
  onToken?: (token: string) => void;
}

/**
 * Typed wrapper around the backend REST API.
 *
 * Auth is injected — the class doesn't know about Keycloak directly (see lib/keycloak-auth.tsx).
 * NDJSON reads use raw `fetch` + `ReadableStream` (needed for streaming; nothing else does, so
 * everything else uses the same `fetch` helper instead of a second, non-streaming HTTP client).
 */
export class ApiClient {
  constructor(
    private baseURL: string = "",
    private auth: Auth = { getToken: () => null }
  ) {}

  private async ensureToken(): Promise<string | null> {
    if (this.auth.refreshToken) {
      try {
        await this.auth.refreshToken();
      } catch {
        /* best-effort refresh, request proceeds with whatever token we have */
      }
    }
    const token = this.auth.getToken() || null;
    if (token && this.auth.onToken) {
      try {
        this.auth.onToken(token);
      } catch {
        /* forwarding the token to the service worker is best-effort */
      }
    }
    return token;
  }

  private async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const token = await this.ensureToken();
    const headers = new Headers(init.headers);
    if (token) headers.set("Authorization", `Bearer ${token}`);
    if (init.body && !headers.has("Content-Type")) headers.set("Content-Type", "application/json");
    const res = await fetch(this.baseURL + path, { ...init, headers });
    if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
    if (res.status === 204 || res.headers.get("Content-Length") === "0") return undefined as T;
    const text = await res.text();
    return text ? (JSON.parse(text) as T) : (undefined as T);
  }

  // -- Direct image URLs -------------------------------------------------------
  // Preferred path: the service worker (scope `/`) intercepts these endpoints and injects the
  // Authorization header from its cached token, so the JWT never appears in the URL. Fallback:
  // browsers refuse to register a service worker on insecure origins (anything but HTTPS /
  // localhost / 127.0.0.1) — on a plain-HTTP LAN IP there's no SW and no other way for <img>
  // tags to carry an Authorization header, so we fall back to the token in the query string
  // (the backend accepts `?token=` as well as the header — see SecureEndpoints.bearerAuth).
  private imageUrlAuth(): string {
    const insecure = typeof window !== "undefined" && window.isSecureContext === false;
    if (!insecure) return "";
    const t = this.auth.getToken();
    return t ? `?token=${encodeURIComponent(t)}` : "";
  }
  mediaNormalizedUrl(mediaAccessKey: string): string {
    return `/api/media/${encodeURIComponent(mediaAccessKey)}/content/normalized${this.imageUrlAuth()}`;
  }
  mediaMiniatureUrl(mediaAccessKey: string): string {
    return `/api/media/${encodeURIComponent(mediaAccessKey)}/content/miniature${this.imageUrlAuth()}`;
  }
  mediaOriginalUrl(mediaAccessKey: string): string {
    return `/api/media/${encodeURIComponent(mediaAccessKey)}/content/original${this.imageUrlAuth()}`;
  }
  // `version`, when given, is appended as a cache-busting query param. A face's cached crop file
  // can be regenerated in place (e.g. re-cropped after a rotation) while its faceId - and so this
  // URL - stays identical; the response is cached (`Cache-Control: max-age`, see ApiApp.addCacheHeader)
  // keyed on that unchanged URL, so without a version bump the browser can keep serving crop bytes
  // from before the regeneration. Pass something that changes whenever the crop does, e.g. the
  // face's box coordinates.
  faceImageUrl(faceId: string, version?: string): string {
    const auth = this.imageUrlAuth();
    const versionParam = version ? `v=${encodeURIComponent(version)}` : "";
    const query = [auth.startsWith("?") ? auth.slice(1) : "", versionParam].filter(Boolean).join("&");
    return `/api/face/${encodeURIComponent(faceId)}/content${query ? `?${query}` : ""}`;
  }

  // -- Media --------------------------------------------------------------------
  getMedia(select: MediaSelector, referenceMediaAccessKey?: string, referenceMediaTimestamp?: string): Promise<Media> {
    const params = new URLSearchParams({ select });
    if (referenceMediaAccessKey) params.set("referenceMediaAccessKey", referenceMediaAccessKey);
    if (referenceMediaTimestamp) params.set("referenceMediaTimestamp", referenceMediaTimestamp);
    return this.request(`/api/media?${params.toString()}`);
  }
  getMediaByKey(mediaAccessKey: string): Promise<Media> {
    return this.request(`/api/media/${encodeURIComponent(mediaAccessKey)}`);
  }
  updateMedia(mediaAccessKey: string, body: MediaUpdateBody): Promise<void> {
    return this.request(`/api/media/${encodeURIComponent(mediaAccessKey)}`, { method: "PUT", body: JSON.stringify(body) });
  }
  updateMediaStarred(mediaAccessKey: string, state: boolean): Promise<void> {
    return this.request(`/api/media/${encodeURIComponent(mediaAccessKey)}/starred?state=${state}`, { method: "PUT" });
  }
  getMediaFaces(mediaAccessKey: string): Promise<OriginalFaces> {
    return this.request(`/api/media/${encodeURIComponent(mediaAccessKey)}/faces`);
  }
  mediasLocations(onItem: (item: MediaLocation) => void, signal?: AbortSignal): Promise<void> {
    return this.fetchNdjsonStream("/api/medias/locations", onItem, signal);
  }
  // Stream up to `limit` medias starting just after `fromKey`, walking the timestamp index
  // forward (newer) by default, or backward (older) when `backward` is true.
  mediasStreamFromKey(
    fromKey: string,
    opts: { backward?: boolean; limit?: number; signal?: AbortSignal; onItem: (item: Media) => void }
  ): Promise<void> {
    const params = new URLSearchParams({ fromKey });
    if (opts.backward) params.set("backward", "true");
    if (opts.limit && opts.limit > 0) params.set("limit", String(opts.limit));
    return this.fetchNdjsonStream(`/api/medias/stream?${params.toString()}`, opts.onItem, opts.signal);
  }

  // -- State ----------------------------------------------------------------------
  getState(originalId: string): Promise<State> {
    return this.request(`/api/state/${encodeURIComponent(originalId)}`);
  }

  // -- Bags -------------------------------------------------------------------------
  listBags(): Promise<Bag[]> {
    return this.fetchNdjson("/api/bags");
  }
  getBag(bagId: string): Promise<Bag> {
    return this.request(`/api/bag/${encodeURIComponent(bagId)}`);
  }
  updateBag(bagId: string, body: BagUpdate): Promise<void> {
    return this.request(`/api/bag/${encodeURIComponent(bagId)}`, { method: "PUT", body: JSON.stringify(body) });
  }
  setBagCover(bagId: string, mediaAccessKey: string): Promise<void> {
    return this.request(`/api/bag/${encodeURIComponent(bagId)}/cover/${encodeURIComponent(mediaAccessKey)}`, { method: "PUT" });
  }

  // -- Owners -------------------------------------------------------------------------
  listOwners(): Promise<Owner[]> {
    return this.fetchNdjson("/api/owners");
  }
  getOwner(ownerId: string): Promise<Owner> {
    return this.request(`/api/owner/${encodeURIComponent(ownerId)}`);
  }
  createOwner(body: OwnerCreate): Promise<Owner> {
    return this.request("/api/owner", { method: "POST", body: JSON.stringify(body) });
  }
  updateOwner(ownerId: string, body: OwnerUpdate): Promise<void> {
    return this.request(`/api/owner/${encodeURIComponent(ownerId)}`, { method: "PUT", body: JSON.stringify(body) });
  }
  setOwnerCover(ownerId: string, mediaAccessKey: string): Promise<void> {
    return this.request(`/api/owner/${encodeURIComponent(ownerId)}/cover/${encodeURIComponent(mediaAccessKey)}`, { method: "PUT" });
  }

  // -- Persons -------------------------------------------------------------------------
  listPersons(): Promise<Person[]> {
    return this.fetchNdjson("/api/persons");
  }
  getPerson(personId: string): Promise<Person> {
    return this.request(`/api/person/${encodeURIComponent(personId)}`);
  }
  createPerson(body: PersonCreate): Promise<Person> {
    return this.request("/api/person", { method: "POST", body: JSON.stringify(body) });
  }
  updatePerson(personId: string, body: PersonUpdate): Promise<void> {
    return this.request(`/api/person/${encodeURIComponent(personId)}`, { method: "PUT", body: JSON.stringify(body) });
  }
  deletePerson(personId: string): Promise<void> {
    return this.request(`/api/person/${encodeURIComponent(personId)}`, { method: "DELETE" });
  }
  updatePersonFace(personId: string, faceId: string): Promise<void> {
    return this.request(`/api/person/${encodeURIComponent(personId)}/face/${encodeURIComponent(faceId)}`, { method: "PUT" });
  }
  listPersonFaces(personId: string): Promise<DetectedFace[]> {
    return this.fetchNdjson(`/api/person/${encodeURIComponent(personId)}/faces`);
  }

  // -- Faces -------------------------------------------------------------------------
  listFaces(): Promise<DetectedFace[]> {
    return this.fetchNdjson("/api/faces");
  }
  getFace(faceId: string): Promise<DetectedFace> {
    return this.request(`/api/face/${encodeURIComponent(faceId)}`);
  }
  createFace(body: FaceCreate): Promise<DetectedFace> {
    return this.request("/api/face", { method: "POST", body: JSON.stringify(body) });
  }
  deleteFace(faceId: string): Promise<void> {
    return this.request(`/api/face/${encodeURIComponent(faceId)}`, { method: "DELETE" });
  }
  setFacePerson(faceId: string, personId: string): Promise<void> {
    return this.request(`/api/face/${encodeURIComponent(faceId)}/person/${encodeURIComponent(personId)}`, { method: "PUT" });
  }
  removeFacePerson(faceId: string): Promise<void> {
    return this.request(`/api/face/${encodeURIComponent(faceId)}/person`, { method: "DELETE" });
  }
  ignoreFace(faceId: string): Promise<void> {
    return this.request(`/api/face/${encodeURIComponent(faceId)}/ignore`, { method: "PUT" });
  }
  restoreFace(faceId: string): Promise<void> {
    return this.request(`/api/face/${encodeURIComponent(faceId)}/ignore`, { method: "DELETE" });
  }

  // -- Stores -------------------------------------------------------------------------
  listStores(): Promise<Store[]> {
    return this.fetchNdjson("/api/stores");
  }
  getStore(storeId: string): Promise<Store> {
    return this.request(`/api/store/${encodeURIComponent(storeId)}`);
  }
  createStore(body: StoreCreate): Promise<Store> {
    return this.request("/api/store", { method: "POST", body: JSON.stringify(body) });
  }
  updateStore(storeId: string, body: StoreUpdate): Promise<void> {
    return this.request(`/api/store/${encodeURIComponent(storeId)}`, { method: "PUT", body: JSON.stringify(body) });
  }

  // -- Portfolios -------------------------------------------------------------------------
  listPortfolios(): Promise<Portfolio[]> {
    return this.fetchNdjson("/api/portfolios");
  }
  getPortfolio(portfolioId: string): Promise<Portfolio> {
    return this.request(`/api/portfolio/${encodeURIComponent(portfolioId)}`);
  }
  createPortfolio(body: PortfolioCreate): Promise<Portfolio> {
    return this.request("/api/portfolio", { method: "POST", body: JSON.stringify(body) });
  }
  updatePortfolio(portfolioId: string, body: PortfolioUpdate): Promise<void> {
    return this.request(`/api/portfolio/${encodeURIComponent(portfolioId)}`, { method: "PUT", body: JSON.stringify(body) });
  }
  deletePortfolio(portfolioId: string): Promise<void> {
    return this.request(`/api/portfolio/${encodeURIComponent(portfolioId)}`, { method: "DELETE" });
  }
  addPortfolioAsset(portfolioId: string, body: Asset): Promise<Asset> {
    return this.request(`/api/portfolio/${encodeURIComponent(portfolioId)}/asset`, { method: "POST", body: JSON.stringify(body) });
  }
  updatePortfolioAsset(portfolioId: string, oldAsset: Asset, newAsset: Asset): Promise<Asset> {
    return this.request(`/api/portfolio/${encodeURIComponent(portfolioId)}/asset`, {
      method: "PUT",
      body: JSON.stringify({ oldAsset, newAsset }),
    });
  }
  removePortfolioAsset(portfolioId: string, body: Asset): Promise<void> {
    return this.request(`/api/portfolio/${encodeURIComponent(portfolioId)}/asset`, { method: "DELETE", body: JSON.stringify(body) });
  }

  // -- Sync admin -------------------------------------------------------------------------
  synchronizeStatus(): Promise<SynchronizeStatus> {
    return this.request("/api/admin/synchronize");
  }
  synchronizeStart(addedThoseLastDays?: number): Promise<void> {
    const params = new URLSearchParams();
    if (typeof addedThoseLastDays === "number" && Number.isFinite(addedThoseLastDays)) {
      params.set("addedThoseLastDays", String(addedThoseLastDays));
    }
    const qs = params.toString();
    return this.request(`/api/admin/synchronize${qs ? `?${qs}` : ""}`, { method: "PUT" });
  }

  // -- NDJSON helpers -------------------------------------------------------------------------
  private async fetchNdjson<T>(url: string): Promise<T[]> {
    const results: T[] = [];
    await this.fetchNdjsonStream<T>(url, (item) => results.push(item));
    return results;
  }

  private async fetchNdjsonStream<T>(url: string, onItem: (item: T) => void, signal?: AbortSignal): Promise<void> {
    const token = await this.ensureToken();
    const headers: HeadersInit = token ? { Authorization: `Bearer ${token}` } : {};
    const res = await fetch(this.baseURL + url, { headers, signal });
    if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
    const reader = res.body!.getReader();
    const decoder = new TextDecoder("utf-8");
    let buffer = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      let idx: number;
      while ((idx = buffer.indexOf("\n")) >= 0) {
        const line = buffer.slice(0, idx);
        buffer = buffer.slice(idx + 1);
        if (line.trim()) {
          try {
            onItem(JSON.parse(line) as T);
          } catch (e) {
            console.error("NDJSON parse error", e);
          }
        }
      }
    }
    if (buffer.trim()) {
      try {
        onItem(JSON.parse(buffer) as T);
      } catch {
        /* trailing partial line, ignore */
      }
    }
  }
}
